name: Update F-Droid Repo
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install F-Droid Server
        run: sudo apt-get update && sudo apt-get install -y fdroidserver

      - name: Generate Repo Index
        run: |
          # Si no hay configuración, la creamos una sola vez
          if [ ! -f "config.yml" ]; then
            fdroid init --distinguished-name "CN=Mi Repo Personal, OU=F-Droid"
          fi
          
          # Actualizamos el índice usando la llave que se acaba de crear
          fdroid update -c
        working-directory: .

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: repo
          branch: gh-pages
